### ISSUE TITLE
Order insignificant sequence equality comparison

### ISSUE THREAD

**Issue by franklin-ross** [StephenCleary/Comparers#1]
Hey there,

I've got an extension function which has been kicking around in my LinqPad extensions for while which is basically your .EquateSequence() function, except that it allows the significance of element order to be specified. It takes duplicate elements in each sequence into account when order is not significant, otherwise it just uses System.Linq.Enumerable.SequenceEqual() for order significant equality.

I'd be happy to give you the code, or submit a pull request or something if you'd like to include it in your library?

Cheers,
Frank.

**Comment by StephenCleary** [comment]
Updated links due to user rename:
  https://gist.github.com/franklin-ross/e57a2e834f1c8ddd6240#file-order-insignificant-sequence-comparer
  https://gist.github.com/franklin-ross/51d4ffe268c928ee55a9#file-tests-for-order-insignificant-sequence-compare

**Comment by StephenCleary** [comment]
It seems to me that populating collections would be surprising behavior for a comparer. I think this would be best left as an explicit add-on, rather than part of the comparer core.
