### ISSUE TITLE
EquatableBaseWithOperators: System.NullReferenceException : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by yinyue200** [StephenCleary/Comparers#11]
```
    class Test:Nito.Comparers.EquatableBaseWithOperators<Test>
    {
        static Test()
        {
            DefaultComparer = Nito.Comparers.EqualityComparerBuilder.For<Test>().Default();
        }
    }
        [Fact]
        public void Test1()
        {
            Test a = null;
            Assert.True(a == null);
        }
```
[this code ](https://github.com/yinyue200/nito.comparer.bug1)failed with

>        System.NullReferenceException : Object reference not set to an instance of an object.
>        Stack Trace:
>             at Nito.Comparers.Util.ComparableImplementations.ImplementOpEquality[T](IEqualityComparer`1 equalityComparer, T left, T right)

**Comment by StephenCleary** [comment]
In this code, the static `Test` constructor is never called, so `Test.DefaultComparer` is `null`.

You have to force the `Test` constructor to be called, e.g., by creating a `Test` instance:

```C#
[Fact]
public void Test1()
{
  var _ = new Test();
  Test a = null;
  Assert.True(a == null);
}
```
