### ISSUE TITLE
Avoid unnecessary dependencies in .NET 4.5

### ISSUE THREAD

**Issue by franklin-ross** [StephenCleary/Comparers#5]
I've been using this package for a while and it's great, but when I recently added it to a .NET 4.5 app, it pulled in a whole lot of .NET standard dependencies (more than doubled my packages list), even though I don't believe it strictly needs them (could be wrong there).

[From this SO post I'm guess it might be possible to create a package that only installs those dependencies if it needs them](https://stackoverflow.com/questions/42855180/how-to-create-net-standard-nuget-package-with-minimal-dependencies-in-vs-2017).

Thoughts?

**Comment by StephenCleary** [comment]
Yes, it's possible. But it's a lot of work, and I expect the RTM of the netstandard tooling to resolve this automatically.

If they don't, then I'll revisit this.

https://github.com/StephenCleary/AsyncEx/issues/84

**Comment by franklin-ross** [comment]
Yup, that's fair. I was thinking that might be in the works, considering it's a pretty broad issue and seems like it could be automated away.

**Comment by StephenCleary** [comment]
Agreed. I know they're planning for netstandard 2.0 to just have a single dll for all of netstandard. Not sure if that will be (or even can be) backported to netstandard 1.x.

But I'm hoping they'll fix up the netstandard tooling at least.
