### ISSUE TITLE
Equality String Comparer Ignore Case

### ISSUE THREAD

**Issue by FutureTD** [StephenCleary/Comparers#9]
Is there a way to make the string equality comparer case insensitive using the StringComparison.OrdinalIgnoreCase, I would prefer to no have to do .ToUpper() or .ToLower() if possible.

**Comment by StephenCleary** [comment]
Sure; you can pass it as the second parameter to a key comparer.

Using the classic `Person` example, you can do this:

    ComparerBuilder.For<Person>().OrderBy(p => p.LastName, StringComparison.OrdinalIgnoreCase);
